plugins:
  - gilbert.plugins.yaml
  - gilbert.plugins.scss
  - gilbert.plugins.selection

global:
    sitename: Kitty Litter
    url: https://blog.tinbrain.net/

content_type:
  SCSS:
    output_style: 'compressed'
  MarkdownPage:
    - toc
