[project]
name = "kitty-litter"
version = "1.0"
authors = [
    {name = "Curtis Maloney", email="curtis@tinbrain.net"},
]

requires-python = ">3.12"

dependencies = [
    "gilbert",
    "lxml",
    "pygments",
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
